### ISSUE TITLE
[Translation] Blog: Apache Pulsar: A Unified Queueing and Streaming Platform

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#100]
You can directly edit in this docs: https://docs.google.com/document/d/1F7EDEEzvT7uQOAWAXSoCkorfQ020WQwb9SE1J95PmIk/edit?usp=sharing

#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：https://docs.google.com/document/d/1F7EDEEzvT7uQOAWAXSoCkorfQ020WQwb9SE1J95PmIk/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **下周三之前（11 月 17 号前）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by JueShanCoder** [comment]
mark！

**Comment by JipeiWang** [comment]
本周三（12 月 1 日发布）

**Comment by tuhaihe** [comment]
@all-contributors , please add @JueShanCoder  as the contributor for translation
