### ISSUE TITLE
[Translation] Doc：tiered-storage-filesystem

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-user-group-loc-cn#104]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：tiered-storage-filesystem 的部分翻译
文档链接：https://crowdin.com/translate/apache-pulsar/2442/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by yangxuan74** [comment]
您好，我第一次在咱们社区翻译，想尝试一下这篇，可以吗？

**Comment by yangxuan74** [comment]
已翻译完成，请审核。

**Comment by tuhaihe** [comment]
@yangxuan74 已经Review，翻译质量很高，感谢贡献！

**Comment by tuhaihe** [comment]
@all-contributors , please add @yangxuan74  as the contributor for translation
