### ISSUE TITLE
[Translation] Blog: Building Edge Applications With Apache Pulsar

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#105]
You can directly edit in this docs: 
https://docs.google.com/document/d/1woAzKtAi04Fy-1hAenMqkytsI0Mcyi-uoIu-b8aTMEA/edit?usp=sharing

#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1woAzKtAi04Fy-1hAenMqkytsI0Mcyi-uoIu-b8aTMEA/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **周五之前（11 月 26 日前）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by safaf11** [comment]
领105
