### ISSUE TITLE
[Translation] Blog: Distributed Locks with Apache Pulsar

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#108]
You can directly edit in this docs: 
https://docs.google.com/document/d/1HGvw-Pw1WMnhl2XHzQ8uEYSEAnU1vtfXJxoGA4_mwac/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1HGvw-Pw1WMnhl2XHzQ8uEYSEAnU1vtfXJxoGA4_mwac/edit?usp=sharing（🉑️直接在文档上编辑）请尽量在 **本周（11 月 29 日前）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by kivenwei** [comment]
认领

**Comment by kivenwei** [comment]
done, 可以校验了。

**Comment by JipeiWang** [comment]
已经发布啦🙏

**Comment by tuhaihe** [comment]
@all-contributors , please add @kivenwei  as the contributor for translation
