### ISSUE TITLE
[Translation] Blog: Apache BookKeeper Internals — Part 1 — High Level

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#110]
You can directly edit in this docs: 
https://docs.google.com/document/d/1TdOAy3tcMaOru-dPwJiK1YkwsEOzLwZ9mnNaeGmH5bg/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1TdOAy3tcMaOru-dPwJiK1YkwsEOzLwZ9mnNaeGmH5bg/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **本周（11 月 29 日前）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by wangjialing218** [comment]
I'll take this

**Comment by EAHITechnology** [comment]
我要翻译

**Comment by EAHITechnology** [comment]
> 

朋友抱歉，周天之前没有评论，这个在群里当时认领了

**Comment by tuhaihe** [comment]
@all-contributors , please add @wangjialing218  as the contributor for translation
