### ISSUE TITLE
[Translation] Blog: Apache BookKeeper Internals — Part 2 — Writes

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#111]
You can directly edit in this docs: 
https://docs.google.com/document/d/1onjhBcshHbPy8Zr4SaCLNfWq4CrZtHN1ZwhRSW1i2bM/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1onjhBcshHbPy8Zr4SaCLNfWq4CrZtHN1ZwhRSW1i2bM/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **本周（11 月 29 日前）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by EAHITechnology** [comment]
我要翻译

**Comment by autumnqfeng** [comment]
已经翻译完了，刚在SIG-Pulsar_Storage微信群里有交流

**Comment by JipeiWang** [comment]
@autumnqfeng 感谢翻译，我们正在进行最终的审核。文章待发布，翻译质量非常👍

**Comment by JipeiWang** [comment]
审核完毕，已留言，PTAL

**Comment by JipeiWang** [comment]
内容今日发布，此 issue 已完工🤝
