### ISSUE TITLE
[Translation] Blog: Apache BookKeeper Internals — Part 3 — Reads

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#112]
You can directly edit in this docs: 
https://docs.google.com/document/d/1wfi7s0VbqOXCEYz8r8nQ0ccw2DwrBD2lxSndVfB4ZoM/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1wfi7s0VbqOXCEYz8r8nQ0ccw2DwrBD2lxSndVfB4ZoM/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **本周（11 月 29 日前）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by wanglunhui2012** [comment]
认领

**Comment by JipeiWang** [comment]
正在审核中，感谢 @wanglunhui2012 的翻译🤩

**Comment by JipeiWang** [comment]
已发布～，感谢大家的参与。
