### ISSUE TITLE
[Translation] Blog: Apache BookKeeper Internals — Part 4 — Back Pressure

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#113]
You can directly edit in this docs: 
https://docs.google.com/document/d/1hJmopKIYLbWC-fN8lHI52XiT9569DBBfPmGmxHltT1Y/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1hJmopKIYLbWC-fN8lHI52XiT9569DBBfPmGmxHltT1Y/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **本周（11 月 29 日前）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by zeroGozhang** [comment]
mark

**Comment by zeroGozhang** [comment]
done

**Comment by JipeiWang** [comment]
正在审核中，谢谢 @zeroGozhang 的翻译

**Comment by tuhaihe** [comment]
已正式发布：https://mp.weixin.qq.com/s/cXyRP8C-zQwIdFUf1UqV4g
感谢 @zeroGozhang !

**Comment by tuhaihe** [comment]
@allcontributors , please add @zeroGozhang  as the contributor for translation.

**Comment by JipeiWang** [comment]
已发布～谢谢大家
