### ISSUE TITLE
[Translation] Blog: Apache BookKeeper Observability — Part 2 — Write USE Metrics

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#116]
You can directly edit in this docs: 
https://docs.google.com/document/d/1an2-wD19TvC-YMVucr5JegogifxCjb5BsaF6EQPOQ-s/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1an2-wD19TvC-YMVucr5JegogifxCjb5BsaF6EQPOQ-s/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 12 月上旬完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by AhahaGe** [comment]
please assign to me

**Comment by JueShanCoder** [comment]
let me try it.

**Comment by Tango2018cc** [comment]
提醒认领的小伙伴别忘了本篇Blog翻译哈～

**Comment by Sherlock113** [comment]
Thank you for your translation. This blog is being reviewed right now. @JueShanCoder Thx~

**Comment by JipeiWang** [comment]
hello @JueShanCoder ，文章已进入发布档期，我们先进行发布啦。麻烦方便的时候确认一下哦
