### ISSUE TITLE
[Translation] Blog: Apache BookKeeper Observability — Part 3 — Write Metrics in Detail

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#117]
You can directly edit in this docs: 
https://docs.google.com/document/d/1o9wpDIiDy6NO3Wts6beYxD7qZcVnqeh0-GwAf1NjoFQ/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1o9wpDIiDy6NO3Wts6beYxD7qZcVnqeh0-GwAf1NjoFQ/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 12 月上旬 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by AhahaGe** [comment]
please assign to me

**Comment by complone** [comment]
Translation completed

**Comment by Sherlock113** [comment]
@complone Thank you for your translation. It is being reviewed now.

**Comment by Sherlock113** [comment]
Hi @complone thank you for your translation. Could you please take a look at the existing comments and make the necessary changes to the entire article? As I notice, some translation is not finished. Please refine your translation and I will proceed with the review again. Thanks.

**Comment by complone** [comment]
ok i will finish it today
