### ISSUE TITLE
[Translation] Blog: A Guide to the BookKeeper Replication Protocol (TLA+ Series Part 2)

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#120]
You can directly edit in this docs: 
https://docs.google.com/document/d/1tRYN5J8KuVkTV3ZWIk9dywPjCRAfZzNUMpVww0eRLv8/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1tRYN5J8KuVkTV3ZWIk9dywPjCRAfZzNUMpVww0eRLv8/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **12月上旬** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by wangjialing218** [comment]
mark

**Comment by Tango2018cc** [comment]
文档已经Review过，辛苦抽空确认下，感谢贡献！

**Comment by JipeiWang** [comment]
今天于 Apache Pulsar 公众号发布，感谢嘉凌。
