### ISSUE TITLE
[Translation] Blog: Modelling and verifying the BookKeeper protocol (TLA+ Series Part 3)

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#121]
You can directly edit in this docs: 
https://docs.google.com/document/d/1Zhs_jfb2qHvpUdikU-EwAxAN6DVs4xDljO83g4SqOAQ/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1Zhs_jfb2qHvpUdikU-EwAxAN6DVs4xDljO83g4SqOAQ/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **12月上旬）** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by VinciLee1** [comment]
认领

**Comment by VinciLee1** [comment]
Translation done please review

**Comment by VinciLee1** [comment]
@whqq1711

**Comment by JipeiWang** [comment]
博文审核中 @VinciLee1 🙏
