### ISSUE TITLE
[Translation] Blog: Offset Implementation in Kafka-on-Pulsar

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#161]
You can directly edit in this docs: 
https://docs.google.com/document/d/1-Xx3NOinTyC0YuErPvegEyeoor_-dMEr5ZI2uZOhQMs/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1-Xx3NOinTyC0YuErPvegEyeoor_-dMEr5ZI2uZOhQMs/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **下周四（02.24）前** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by AlphaWang** [comment]
let me try.

**Comment by JipeiWang** [comment]
👍已留言，PTAL

**Comment by JipeiWang** [comment]
已发布，戳[发布链接](https://mp.weixin.qq.com/s?__biz=MzUyMjkzMjA1Ng==&mid=2247490872&idx=1&sn=a695bbc26b72fea0d3701ad57aafc51c&exportkey=A87ejdDdfV06H1BzP%2FmEXpc%3D&acctmode=0&pass_ticket=Af74PK2aE0SxI03C0X36qcjAeeitFQj7QDGulg9n3co%2FRNzWseeekwBvXkYy2JNl&wx_header=0)
