### ISSUE TITLE
[Translation] Blog: Tweaking the BookKeeper Protocol - Unbounded Ledgers

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#163]
You can directly edit in this docs: 
https://docs.google.com/document/d/1sxCyN7RIu_q4PKy1NqOftDovbFjK8ETEsz6X0INs7UY/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1sxCyN7RIu_q4PKy1NqOftDovbFjK8ETEsz6X0INs7UY/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **下周四（02.24）前** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by 602763061** [comment]
claim translate task

**Comment by Sherlock113** [comment]
@602763061 Thank you for your translation. We are reviewing the translation.

**Comment by JipeiWang** [comment]
已发布，谢谢大家

**Comment by JipeiWang** [comment]
发布后关闭本 issue
