### ISSUE TITLE
[Translation] Blog: Moving Toward a ZooKeeper-Less Apache Pulsar

### ISSUE THREAD

**Issue by whqq1711** [streamnative/pulsar-user-group-loc-cn#166]
You can directly edit in this docs: 
https://docs.google.com/document/d/1X1sZaLWYroHchBe_9r8WPcHD-vJi14GIpQwP1v0gg5Y/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1X1sZaLWYroHchBe_9r8WPcHD-vJi14GIpQwP1v0gg5Y/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **下周四（02.24）前** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by VinciLee1** [comment]
认领

**Comment by VinciLee1** [comment]
@Tango2018cc done

**Comment by JipeiWang** [comment]
收到，感谢 @VinciLee1 的翻译😄 我们正在审核中～

**Comment by JipeiWang** [comment]
已留言，@VinciLee1 PTAL。翻译质量非常棒👍👍👍

**Comment by VinciLee1** [comment]
@JipeiWang 感谢Review，收益良多！

**Comment by JipeiWang** [comment]
已发布～
