### ISSUE TITLE
[社区FAQ收集] 2021-12/20-12/31

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-user-group-loc-cn#168]
欢迎大家认领，本任务为社区FAQ的内容收集，耗时5-15min，请接手任务的小伙伴在此 issue 留言并在微信群艾特Tango，管理员会分配 issue，方便记录大家的贡献。

点击下方链接了解本任务详情
https://docs.google.com/document/d/1VBHFgagbYRELvVI--JswU46-L53aM3Qs6AHJ2adI7H8/edit#

**Comment by shibd** [comment]
mark

**Comment by shibd** [comment]
done.

**Comment by Tango2018cc** [comment]
目前已提交Issue 进行Reveiw，近期会更新到FAQ知识库中，此Issue关闭～
