### ISSUE TITLE
[Translation] Blog: Apache BookKeeper Insights Part 2 — Closing Ledgers Safely

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#192]
You can directly edit in this docs:
https://docs.google.com/document/d/1qoxR0WYt9KRO47LmvP9PDRJg6T_x3vKbKP1rBcs8fow/edit?usp=sharing

Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community!

欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1qoxR0WYt9KRO47LmvP9PDRJg6T_x3vKbKP1rBcs8fow/edit?usp=sharing
（🉑️直接在文档上编辑）

**Comment by autumnqfeng** [comment]
我翻译吧

**Comment by JipeiWang** [comment]
谢谢 @autumnqfeng 的翻译，我们正在审核中。
