### ISSUE TITLE
[Translation] Blog: Streaming Real-Time Chat Messages into Scylla with Apache Pulsar

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#193]
You can directly edit in this docs:
https://docs.google.com/document/d/10kFWwcDigw6WONS7FJb1VpoZZ3q8yMK2cDq83-wNZDI/edit?usp=sharing

Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community!

欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：https://docs.google.com/document/d/10kFWwcDigw6WONS7FJb1VpoZZ3q8yMK2cDq83-wNZDI/edit?usp=sharing  （🉑️直接在文档上编辑）

**Comment by Radiancebobo** [comment]
认领！

**Comment by JipeiWang** [comment]
谢谢 @Radiancebobo 的翻译，正在审核中～～～

**Comment by JipeiWang** [comment]
已发布
