### ISSUE TITLE
[Translation] Blog: Apache Pulsar Client Application Best Practices

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#194]
You can directly edit in this docs:
https://docs.google.com/document/d/14MErTU442cDnatRTH-GMia4OyCtOA1JLG6AV-sI63cw/edit?usp=sharing

Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community!

欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：https://docs.google.com/document/d/14MErTU442cDnatRTH-GMia4OyCtOA1JLG6AV-sI63cw/edit?usp=sharing （🉑️直接在文档上编辑）]

**Comment by Radiancebobo** [comment]
认领！

**Comment by tuhaihe** [comment]
本文已发布：https://mp.weixin.qq.com/s/fbB1C_xFKwl5t_Bov33wxA
