### ISSUE TITLE
[Translation] Blog：What the FLiP is the FLiP Stack

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-user-group-loc-cn#201]
You can directly edit in this docs: 
https://docs.google.com/document/d/1WsayEAwg62s6XeLPDbpMrom1JtsJWOmzloHcPUCqkGk/edit#
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1WsayEAwg62s6XeLPDbpMrom1JtsJWOmzloHcPUCqkGk/edit#
（🉑️直接在文档上编辑）请尽量在 **下周四（02.24）前** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by AlphaWang** [comment]
认领 :)

**Comment by AlphaWang** [comment]
Done

**Comment by Tango2018cc** [comment]
感谢贡献，我们会尽快Review

**Comment by JipeiWang** [comment]
谢谢 @AlphaWang 的翻译与讨论，计划近期发布。

**Comment by JipeiWang** [comment]
已发布🙏
