### ISSUE TITLE
[Translation] Blog：Deep Dive into Message Chunking in Pulsar

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#203]
You can directly edit in this docs: 
https://docs.google.com/document/d/1jmMz99iqFmyKfn0s_1TBk8aTZpvG-kJQrpJzG16RsW0/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1jmMz99iqFmyKfn0s_1TBk8aTZpvG-kJQrpJzG16RsW0/edit?usp=sharing
（🉑️直接在文档上编辑）

**Comment by raoluSmile** [comment]
认领

**Comment by raoluSmile** [comment]
完成翻译，可以审阅

**Comment by JipeiWang** [comment]
收到，开始审核。感谢 @raoluSmile 的翻译。

**Comment by JipeiWang** [comment]
@raoluSmile 已留言，请确认

**Comment by raoluSmile** [comment]
已确认 @JipeiWang

**Comment by JipeiWang** [comment]
已发布，感谢大家的合作。
