### ISSUE TITLE
[Translation] Blog: Pulsar Isolation Part IV: Single Cluster Isolation

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#205]
You can directly edit in this docs: 
https://docs.google.com/document/d/1rsVqbdylBKJlH7pIALKilyXEYaCLa0evc0Q8fFRmnAk/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：https://docs.google.com/document/d/1rsVqbdylBKJlH7pIALKilyXEYaCLa0evc0Q8fFRmnAk/edit?usp=sharing
（🉑️直接在文档上编辑）

**Comment by dislazy** [comment]
mark

**Comment by Sherlock113** [comment]
@dislazy Thank you for your translation. It is being reviewed now.
