### ISSUE TITLE
[Translation] Blog: What’s New in Apache Pulsar 2.10.1

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#207]
You can directly edit in this docs: 
https://docs.google.com/document/d/1jiDPw4kwdqePtzFiZ46Oo-kaDQhZQjSp0tyImh4RNXA/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：https://docs.google.com/document/d/1jiDPw4kwdqePtzFiZ46Oo-kaDQhZQjSp0tyImh4RNXA/edit?usp=sharing
（🉑️直接在文档上编辑）

**Comment by raoluSmile** [comment]
Apply for this translation task

**Comment by raoluSmile** [comment]
done @JipeiWang
