### ISSUE TITLE
[Translation] Blog: Integrating a distributed database with event streaming

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#208]
You can directly edit in this docs: 
https://docs.google.com/document/d/1xoJzWVPpeN43cjPsiJinZARsUC90EWTwku3aUkBKrgk/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/1xoJzWVPpeN43cjPsiJinZARsUC90EWTwku3aUkBKrgk/edit?usp=sharing

**Comment by NicoleRobin** [comment]
Apply for this translation task

**Comment by NicoleRobin** [comment]
@JipeiWang done

**Comment by Sherlock113** [comment]
@NicoleRobin Thank you for your translation. It is being reviewed.
