### ISSUE TITLE
[Translation] Blog: Deep Dive into Data Placement Policies

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#209]
You can directly edit in this gdocs: 
https://docs.google.com/document/d/1A7LEYfh177bVlDqcd7IMORe11HVhcz3-dl6LrAT-7j4/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/1A7LEYfh177bVlDqcd7IMORe11HVhcz3-dl6LrAT-7j4/edit?usp=sharing

**Comment by ethqunzhong** [comment]
i will do this blog's translation.

**Comment by ethqunzhong** [comment]
done

**Comment by Sherlock113** [comment]
@ethqunzhong Hi, thank you for your translation. It is being reviewed.

**Comment by ethqunzhong** [comment]
LGTM.
