### ISSUE TITLE
[Translation] Blog: What’s New in Apache Pulsar 2.9.3

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#211]
You can directly edit in this gdocs: 
https://docs.google.com/document/d/18SmqsykPbysmPeGUqno_Ro1FEQpqYsTwcGsD8pPAzwU/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/18SmqsykPbysmPeGUqno_Ro1FEQpqYsTwcGsD8pPAzwU/edit?usp=sharing

**Comment by mangoGoForward** [comment]
认领

**Comment by Sherlock113** [comment]
@mangoGoForward The translation is being reviewed. Thank you!

**Comment by mangoGoForward** [comment]
> @mangoGoForward The translation is being reviewed. Thank you!

@Sherlock113 Confirmed and improved it
