### ISSUE TITLE
[Translation] Blog: Introducing Pulsar Resources Operator for Kubernetes

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#212]
You can directly edit in this gdocs: 
https://docs.google.com/document/d/1orfk--7eX7LtRvtHFdSJiJzpDpiVh-nqd0lD4RX-6K4/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/1orfk--7eX7LtRvtHFdSJiJzpDpiVh-nqd0lD4RX-6K4/edit?usp=sharing

**Comment by NicoleRobin** [comment]
认领

**Comment by NicoleRobin** [comment]
done, pls help review, tks. @JipeiWang

**Comment by JipeiWang** [comment]
审核中～
