### ISSUE TITLE
[Translation] Blog: Understanding Pulsar in 10 Minutes: A Guide for Kafka Users

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#230]
You can directly edit in this docs: 
https://docs.google.com/document/d/1cj0O94KRbnXQ1xeyzxeAPGam6MM9Xq7yuuHZov2DB8c/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：
https://docs.google.com/document/d/1cj0O94KRbnXQ1xeyzxeAPGam6MM9Xq7yuuHZov2DB8c/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在 **12月上旬** 完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by AlphaWang** [comment]
认领

**Comment by JipeiWang** [comment]
开始审核～ @AlphaWang 🙏
