### ISSUE TITLE
[Translation] Blog: Announcing Spring for Apache Pulsar

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#231]
You can directly edit in this gdocs: 
https://docs.google.com/document/d/1V-RsaMyiFYr9Gnb5jOqMAMpDfhSGzk64VWohmcsUZ3s/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/1V-RsaMyiFYr9Gnb5jOqMAMpDfhSGzk64VWohmcsUZ3s/edit?usp=sharing

**Comment by AlphaWang** [comment]
认领

**Comment by AlphaWang** [comment]
done

**Comment by Sherlock113** [comment]
@AlphaWang Thank you for your translation. It is being reviewed.

**Comment by JipeiWang** [comment]
文章已于微信公众号发布，谢谢大家
