### ISSUE TITLE
[Translation] Blog: The Beauty of Apache Pulsar: Individual Message Acknowledgment

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#232]
You can directly edit in this gdocs: 
https://docs.google.com/document/d/1hRaGltU3rR5MfpVfcyAyDcSMbjC32vAUN0KlTZ0wr7U/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/1hRaGltU3rR5MfpVfcyAyDcSMbjC32vAUN0KlTZ0wr7U/edit?usp=sharing

**Comment by AlphaWang** [comment]
认领

**Comment by AlphaWang** [comment]
done

**Comment by Sherlock113** [comment]
Thanks @AlphaWang The translation is being reviewed now.

**Comment by JipeiWang** [comment]
文章今天于公众号发布，谢谢大家
