### ISSUE TITLE
[Translation] Blog: A Deep Dive into the Topic Data Lifecycle in Apache Pulsar

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#233]
You can directly edit in this gdocs: 
https://docs.google.com/document/d/12alNovh4gJXQ7dR_72GhbJm595CUHBSndxrin7KdrTE/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/12alNovh4gJXQ7dR_72GhbJm595CUHBSndxrin7KdrTE/edit?usp=sharing

**Comment by Radiancebobo** [comment]
领

**Comment by Sherlock113** [comment]
@Radiancebobo Thank you for your translation. The blog is being reviewed right now.
