### ISSUE TITLE
[Translation] Blog: How to Migrate from RabbitMQ to Apache Pulsar™

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#237]
You can directly edit in this gdocs: 
hhttps://docs.google.com/document/d/1TKWxoznXfcsBtDzfGP7AGYr3fd7UFhQkvPWyc477rTg/edit?usp=sharing
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/1TKWxoznXfcsBtDzfGP7AGYr3fd7UFhQkvPWyc477rTg/edit?usp=sharing

**Comment by dros6** [comment]
认领翻译

**Comment by Sherlock113** [comment]
@dros6 Thank you for your translation. It is being reviewed.
