### ISSUE TITLE
[Translation] Blog: Announcing the Iceberg Sink Connector for Apache Pulsar

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#243]
You can directly edit in this gdocs:
https://docs.google.com/document/d/1xGOjLGkKepfLFZyBagRZ_ApUEjQ_O2fxg4aBm6vw7Jg/edit?usp=sharing
Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community!

欢迎小伙伴加入 Pulsar 志愿者团队！🉑️直接在文档上编辑
本次博客翻译文档链接：https://docs.google.com/document/d/1xGOjLGkKepfLFZyBagRZ_ApUEjQ_O2fxg4aBm6vw7Jg/edit?usp=sharing

**Comment by ethqunzhong** [comment]
I am working on pulsar-with-iceberg recently. i will take this.

**Comment by ethqunzhong** [comment]
done
