### ISSUE TITLE
[Translation] Doc：FUNCTIONS-RUNTIME

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-user-group-loc-cn#36]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：FUNCTIONS-RUNTIME 的翻译
文档链接：https://crowdin.com/translate/apache-pulsar/660/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by pisceslj** [comment]
认领

**Comment by Tango2018cc** [comment]
已经完成

**Comment by Tango2018cc** [comment]
@all-contributors , please add @pisceslj  as the contributor for translation
