### ISSUE TITLE
[Translation] Doc：io-jdbc-sink

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-user-group-loc-cn#47]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：io-idbc-sink 的翻译
文档链接：https://crowdin.com/translate/apache-pulsar/910/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by FieldChan** [comment]
+1

**Comment by FieldChan** [comment]
I've finished translation, could you please help review?

**Comment by Tango2018cc** [comment]
@all-contributors , please add @FieldChan  as the contributor for translation
