### ISSUE TITLE
[Translation] Blog: Scalable Stream Processing with Pulsar’s Key_Shared Subscription

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#72]
You can directly edit in this docs(template included): https://docs.google.com/document/d/1Qu82n1m_mfnMTY--sxKZ980zXYXxf3kj/edit?usp=sharing&ouid=110299836475637509637&rtpof=true&sd=true
#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
感谢小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：https://docs.google.com/document/d/1Qu82n1m_mfnMTY--sxKZ980zXYXxf3kj/edit?usp=sharing&ouid=110299836475637509637&rtpof=true&sd=true
（🉑️直接在文档上编辑）

**Comment by JueShanCoder** [comment]
Mark ~
Tks ~

**Comment by duanjia85** [comment]
认领

**Comment by JipeiWang** [comment]
已发布，感谢大家！

**Comment by Tango2018cc** [comment]
@all-contributors , please add @duanjia85 、 @JueShanCoder as the contributor for translation

**Comment by Tango2018cc** [comment]
@all-contributors , please add @JueShanCoder as the contributor for translation
