### ISSUE TITLE
[Translation] Doc：io-redis-sink

### ISSUE THREAD

**Issue by Tango2018cc** [streamnative/pulsar-user-group-loc-cn#76]
感谢小伙伴加入 Pulsar 志愿者团队！

本篇为文档：io-redis-sink 的部分翻译
文档链接：https://crowdin.com/translate/apache-pulsar/922/en-zhcn?filter=basic&value=0

请接手任务的小伙伴在此 issue 留言并在微信群艾特我们，管理员会分配 issue，方便记录大家的贡献。

**Comment by dislazy** [comment]
mark

**Comment by Tango2018cc** [comment]
文档内容有更新，欢迎其他小伙伴留言认领

**Comment by Radiancebobo** [comment]
认领

**Comment by Tango2018cc** [comment]
本篇已完成，感谢各位贡献～
