### ISSUE TITLE
[Translation] Blog: Streaming Data Pipelines with Pulsar IO

### ISSUE THREAD

**Issue by JipeiWang** [streamnative/pulsar-user-group-loc-cn#99]
You can directly edit in this docs: https://docs.google.com/document/d/1P_ue8uqPnET5Ikxzo5y7ID6rjqPSF0YRKm2cnBBfDLM/edit?usp=sharing

#### Please comment and ping us in WeChat group if you take over the task. Many thanks for your contribution and joining the Pulsar community! 

---
欢迎小伙伴加入 Pulsar 志愿者团队！
本次博客翻译文档链接：https://docs.google.com/document/d/1P_ue8uqPnET5Ikxzo5y7ID6rjqPSF0YRKm2cnBBfDLM/edit?usp=sharing
（🉑️直接在文档上编辑）请尽量在**下周三 11 月 17 号前**完成翻译工作，为发布前的工程师、编辑审核留出时间，感谢～

**Comment by dislazy** [comment]
mark

**Comment by Tango2018cc** [comment]
已完成

@all-contributors , please add @dislazy  as the contributor for translation
